export const DATABASE_ID = process.env.NEXT_PUBLIC_APP_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APP_APPWRITE_COLLECTION_ID!;
export const BUCKETID = process.env.NEXT_PUBLIC_APP_APPWRITE_BUCKETID!;
export const MEMBER_ID = process.env.NEXT_PUBLIC_APP_APPWRITE_MEMBERS_ID!;