import { client } from "@/lib/rpc";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { InferResponseType, InferRequestType } from "hono/client";
import { toast } from "sonner";

// We extract the exact types generated by Hono RPC for the DELETE endpoint
type ResponseType = InferResponseType<typeof client.api.tasks[":taskId"]["$delete"], 200>;
type RequestType = InferRequestType<typeof client.api.tasks[":taskId"]["$delete"]>;

export const useDeleteTask = () => {
  const queryClient = useQueryClient();

  return useMutation<ResponseType, Error, RequestType>({
    mutationFn: async ({ param }) => {
      const response = await client.api.tasks[":taskId"]["$delete"]({
        param, // Contains { taskId: "..." }
      });

      if (!response.ok) throw new Error("Failed to delete task");

      return await response.json();
    },

    onSuccess: () => {
      toast.success("Task deleted");
      // Invalidate the tasks list so the deleted item is removed from the UI
      queryClient.invalidateQueries({ queryKey: ["tasks"] });
    },

    onError: () => {
      toast.error("Failed to delete task");
    },
  });
};