import { client } from "@/lib/rpc";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { InferResponseType, InferRequestType } from "hono/client";
import { toast } from "sonner";

// We extract the exact types generated by Hono RPC for the PATCH endpoint
type ResponseType = InferResponseType<
  (typeof client.api.tasks)[":taskId"]["$patch"],
  200
>;
type RequestType = InferRequestType<
  (typeof client.api.tasks)[":taskId"]["$patch"]
>;

export const useUpdateTask = () => {
  const queryClient = useQueryClient();

  return useMutation<ResponseType, Error, RequestType>({
    mutationFn: async ({ param, json }) => {
      const response = await client.api.tasks[":taskId"]["$patch"]({
        param, // Contains { taskId: "..." }
        json, // Contains the updated fields
      });

      if (!response.ok) throw new Error("Failed to update task");

      return await response.json();
    },

    onSuccess: () => {
      toast.success("Task updated");
      queryClient.invalidateQueries({ queryKey: ["tasks"] });
    },

    onError: () => {
      toast.error("Failed to update task");
      // Re-fetch to revert optimistic UI back to real server state
      queryClient.invalidateQueries({ queryKey: ["tasks"] });
    },
  });
};
